# Generated by Django 5.0.1 on 2025-11-27 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blockeddate", options={"ordering": ["start_date"]},
        ),
        migrations.AlterModelOptions(
            name="booking", options={"ordering": ["-check_in_date"]},
        ),
        migrations.RemoveField(model_name="booking", name="total_amount",),
        migrations.AddField(
            model_name="booking",
            name="released_from_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=10
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blockeddate",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blocked_dates_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="blockeddate",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="blockeddate",
            name="reason",
            field=models.CharField(
                choices=[
                    ("maintenance", "Maintenance"),
                    ("owner_use", "Owner Use"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="cancellation_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="cleaning_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="booking",
            name="guest_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="internal_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="number_of_guests",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="booking",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Unpaid"),
                    ("partial", "Partial"),
                    ("paid", "Paid"),
                    ("refunded", "Refunded"),
                    ("partially_refunded", "Partially Refunded"),
                ],
                default="unpaid",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="special_requests",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("paid", "Paid"),
                    ("checked_in", "Checked In"),
                    ("checked_out", "Checked Out"),
                    ("cancelled", "Cancelled"),
                    ("no_show", "No-Show"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="tourist_tax",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddConstraint(
            model_name="blockeddate",
            constraint=models.CheckConstraint(
                check=models.Q(("end_date__gte", models.F("start_date"))),
                name="end_date_after_start_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                check=models.Q(("check_out_date__gt", models.F("check_in_date"))),
                name="check_out_after_check_in",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                check=models.Q(("total_price__gte", 0)), name="total_price_non_negative"
            ),
        ),
    ]
