# Generated by Django 5.0.1 on 2025-11-28 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_alter_blockeddate_options_alter_booking_options_and_more"),
        ("bookings", "0003_guest_country_bookinggguest"),
    ]

    operations = []
