# Generated by Django 5.0.1 on 2025-11-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_merge_20251128_1754"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booking_source",
            field=models.CharField(
                choices=[
                    ("airbnb", "Airbnb"),
                    ("booking_com", "Booking.com"),
                    ("website", "Own Website"),
                    ("direct", "Direct"),
                    ("other", "Other"),
                ],
                default="direct",
                help_text="Source of the booking (Airbnb, Booking.com, website, etc.)",
                max_length=20,
            ),
        ),
    ]
