# Generated by Django 4.2.26 on 2025-12-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_booking_guest_tax_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="issue_refund",
            field=models.BooleanField(
                default=False,
                help_text="Whether to issue refund when cancelling this booking",
            ),
        ),
    ]
