# Generated by Django 5.2 on 2025-12-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0007_booking_issue_refund"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="cancellation_policy",
            field=models.CharField(
                choices=[
                    ("flex_24h", "Flexible - free until 24h"),
                    ("non_refundable", "Non-refundable - discounted"),
                ],
                default="flex_24h",
                help_text="Cancellation policy selected by guest",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="is_non_refundable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bookingguest",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bookingguest",
            name="country_of_birth",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="bookingguest",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bookingguest",
            name="document_expire_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bookingguest",
            name="document_issue_country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="bookingguest",
            name="document_issue_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bookingguest",
            name="document_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="bookingguest",
            name="document_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("passport", "Passport"),
                    ("id_card", "ID Card"),
                    ("driving_license", "Driving License"),
                    ("residence_permit", "Residence Permit"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
