# Generated by Django 5.2 on 2025-12-08 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0008_booking_cancellation_policy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingguest",
            name="parent_guest",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent/primary guest for tree view",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="family_members",
                to="bookings.bookingguest",
            ),
        ),
        migrations.AddField(
            model_name="bookingguest",
            name="relationship",
            field=models.CharField(
                blank=True,
                help_text="Relationship to primary guest",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="bookingguest",
            index=models.Index(fields=["parent_guest"], name="bookings_bo_parent_idx"),
        ),
    ]
