# Generated by Django 4.2.26 on 2025-12-08 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0011_bookingattempt"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="bookingattempt",
            new_name="bookings_at_stripe__510353_idx",
            old_name="bookings_at_stripe__c85b52_idx",
        ),
        migrations.RenameIndex(
            model_name="bookingattempt",
            new_name="bookings_at_status_0fc4c2_idx",
            old_name="bookings_at_status_81d8c9_idx",
        ),
        migrations.RenameIndex(
            model_name="bookingattempt",
            new_name="bookings_at_guest_e_5e0aae_idx",
            old_name="bookings_at_guest_e_7a0736_idx",
        ),
    ]
