# Generated by Django 4.2.26 on 2025-12-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bookings",
            "0012_rename_bookings_at_stripe__c85b52_idx_bookings_at_stripe__510353_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="city_tax_paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="city_tax_payment_intent",
            field=models.CharField(
                blank=True,
                help_text="Stripe payment intent/session for city tax",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="city_tax_payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Unpaid"),
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("refunded", "Refunded"),
                ],
                default="unpaid",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="eta_checkin_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="eta_checkout_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
