# Generated by Django 4.2.26 on 2025-12-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0013_booking_city_tax_paid_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="checkin_draft",
            field=models.BooleanField(
                default=False,
                help_text="Online check-in saved as draft (team can review/complete)",
            ),
        ),
    ]
