# Generated by Django 4.2.26 on 2025-12-10 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookings", "0014_booking_checkin_draft"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="alloggiati_sent",
            field=models.BooleanField(
                default=False,
                help_text="Whether guest data has been sent to Italian police (Alloggiati)",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="alloggiati_sent_at",
            field=models.DateTimeField(
                blank=True, help_text="When the data was sent to Alloggiati", null=True
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="alloggiati_sent_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Team member who sent the data to police",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alloggiati_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
