# Generated by Django 5.2 on 2025-12-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_booking_alloggiati_sent_booking_alloggiati_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='review_requested_at',
            field=models.DateTimeField(blank=True, help_text='When review request email was sent', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='review_submitted',
            field=models.BooleanField(default=False, help_text='Whether guest submitted a review for this booking'),
        ),
        migrations.AddField(
            model_name='booking',
            name='review_token',
            field=models.CharField(blank=True, db_index=True, help_text='UUID4 token for review submission link (sent in email)', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='review_token_expires_at',
            field=models.DateTimeField(blank=True, help_text='Review token expiry (30 days from email send)', null=True),
        ),
    ]
