# Generated by Django 4.2.26 on 2025-12-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bookings",
            "0016_booking_review_requested_at_booking_review_submitted_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="adults",
            field=models.IntegerField(
                default=2, help_text="Number of adult guests (13+)"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="children",
            field=models.IntegerField(default=0, help_text="Number of children (2-12)"),
        ),
        migrations.AddField(
            model_name="booking",
            name="infants",
            field=models.IntegerField(
                default=0, help_text="Number of infants (0-2, free)"
            ),
        ),
    ]
