# Generated by Django 4.2.26 on 2025-12-12 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0017_booking_adults_booking_children_booking_infants"),
        ("bookings", "0017_booking_booked_for_someone_else"),
    ]

    operations = []
