# Generated by Django 4.2.26 on 2025-12-12 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0018_booking_pet_fee"),
        ("bookings", "0018_merge_20251212_2036"),
    ]

    operations = []
