# Generated by Django 4.2.26 on 2025-12-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0020_merge_20251213_0405"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="icalsource", options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="icalsource",
            index=models.Index(
                fields=["sync_status"], name="bookings_ic_sync_st_e389c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="icalsource",
            index=models.Index(
                fields=["last_synced"], name="bookings_ic_last_sy_e68a19_idx"
            ),
        ),
        migrations.AlterModelTable(name="icalsource", table="bookings_icalsource",),
    ]
