# Generated by Django 4.2.26 on 2025-12-03 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookings", "0006_booking_guest_tax_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="CleaningSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(help_text="Date when cleaning is scheduled"),
                ),
                (
                    "scheduled_time",
                    models.TimeField(help_text="Time when cleaning should start"),
                ),
                (
                    "estimated_duration",
                    models.IntegerField(
                        default=120, help_text="Estimated duration in minutes"
                    ),
                ),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actual_duration",
                    models.IntegerField(
                        blank=True, help_text="Actual duration in minutes", null=True
                    ),
                ),
                (
                    "quality_rating",
                    models.IntegerField(
                        blank=True, help_text="Quality rating from 1-5", null=True
                    ),
                ),
                ("quality_notes", models.TextField(blank=True)),
                ("inspected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about this cleaning"
                    ),
                ),
                (
                    "special_instructions",
                    models.TextField(
                        blank=True, help_text="Special instructions for the cleaner"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cleaner assigned to this task",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_cleanings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated booking (if triggered by checkout)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cleaning_schedules",
                        to="bookings.booking",
                    ),
                ),
                (
                    "inspected_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who inspected the cleaning",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspected_cleanings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_date", "-scheduled_time"],
                "permissions": [
                    ("view_cleaning", "Can view cleaning schedules"),
                    ("add_cleaning", "Can add cleaning schedules"),
                    ("change_cleaning", "Can change cleaning schedules"),
                    ("delete_cleaning", "Can delete cleaning schedules"),
                    ("assign_cleaning", "Can assign cleanings to staff"),
                    ("inspect_cleaning", "Can inspect and rate cleanings"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CleaningTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(help_text="Task title", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Detailed description"),
                ),
                (
                    "category",
                    models.CharField(
                        default="general",
                        help_text="Task category (e.g., bedroom, bathroom, kitchen)",
                        max_length=50,
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Notes about task completion"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cleaning_schedule",
                    models.ForeignKey(
                        help_text="Parent cleaning schedule",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="cleaning.cleaningschedule",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["cleaning_schedule", "is_completed"],
                        name="cleaning_cl_cleanin_79deef_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="cleaningschedule",
            index=models.Index(
                fields=["scheduled_date", "status"],
                name="cleaning_cl_schedul_357527_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cleaningschedule",
            index=models.Index(
                fields=["assigned_to", "status"], name="cleaning_cl_assigne_93b5d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cleaningschedule",
            index=models.Index(fields=["status"], name="cleaning_cl_status_f413b8_idx"),
        ),
    ]
