# Generated by Django 4.2.26 on 2025-12-10 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cleaning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cleaningschedule",
            name="completed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who completed this cleaning",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="completed_cleanings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
