# Generated by Django 4.2.26 on 2025-12-13 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_user_id_05b4bc_idx",
            old_name="notificatio_user_id_9c1e89_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_user_id_427e4b_idx",
            old_name="notificatio_user_id_4f5a8b_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_booking_c67fcc_idx",
            old_name="notificatio_booking_1a2b3c_idx",
        ),
    ]
