# Generated by Django 5.0.2 on 2025-11-26 07:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('nightly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pricing Rule',
                'verbose_name_plural': 'Pricing Rules',
                'db_table': 'pricing_pricingrule',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.IntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('default_nightly_rate', models.DecimalField(decimal_places=2, default=150.0, max_digits=10)),
                ('cleaning_fee', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('tourist_tax_per_person_per_night', models.DecimalField(decimal_places=2, default=3.5, max_digits=6)),
                ('minimum_stay_nights', models.IntegerField(default=2)),
                ('maximum_stay_nights', models.IntegerField(default=30)),
                ('check_in_time', models.TimeField(default='15:00')),
                ('check_out_time', models.TimeField(default='11:00')),
                ('max_guests', models.IntegerField(default=4)),
                ('extra_guest_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('extra_guest_threshold', models.IntegerField(default=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
                'db_table': 'pricing_settings',
            },
        ),
    ]
