# Generated by Django 5.2 on 2025-12-08 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0004_promotion_voucher_promousage"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="promotion",
            new_name="pricing_pro_code_a5fee6_idx",
            old_name="pricing_pro_code_f9e0e8_idx",
        ),
        migrations.RenameIndex(
            model_name="promotion",
            new_name="pricing_pro_is_acti_8f13a6_idx",
            old_name="pricing_pro_is_acti_6e4072_idx",
        ),
        migrations.RenameIndex(
            model_name="promotion",
            new_name="pricing_pro_expires_3f93ad_idx",
            old_name="pricing_pro_expires_0de58a_idx",
        ),
        migrations.RenameIndex(
            model_name="promousage",
            new_name="pricing_pro_code_ty_7b46f6_idx",
            old_name="pricing_pro_code_ty_bd5b39_idx",
        ),
        migrations.RenameIndex(
            model_name="promousage",
            new_name="pricing_pro_guest_e_269e6c_idx",
            old_name="pricing_pro_guest_e_b18e7a_idx",
        ),
        migrations.RenameIndex(
            model_name="promousage",
            new_name="pricing_pro_used_at_fffb53_idx",
            old_name="pricing_pro_used_at_80f9b7_idx",
        ),
        migrations.RenameIndex(
            model_name="voucher",
            new_name="pricing_vou_code_c9a5a5_idx",
            old_name="pricing_vou_code_2a2b44_idx",
        ),
        migrations.RenameIndex(
            model_name="voucher",
            new_name="pricing_vou_is_acti_7f6a4e_idx",
            old_name="pricing_vou_is_acti_09cb46_idx",
        ),
        migrations.RenameIndex(
            model_name="voucher",
            new_name="pricing_vou_expires_569413_idx",
            old_name="pricing_vou_expires_11f5e9_idx",
        ),
    ]
