# Generated by Django 4.2.26 on 2025-12-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pricing",
            "0005_rename_pricing_pro_code_f9e0e8_idx_pricing_pro_code_a5fee6_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="pet_cleaning_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
