# Generated by Django 5.0.1 on 2025-11-27 20:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("role_at_time", models.CharField(blank=True, max_length=100)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("auth.login", "User Login"),
                            ("auth.logout", "User Logout"),
                            ("auth.password_reset", "Password Reset"),
                            ("booking.created", "Booking Created"),
                            ("booking.updated", "Booking Updated"),
                            ("booking.status_changed", "Booking Status Changed"),
                            ("booking.cancelled", "Booking Cancelled"),
                            ("booking.marked_no_show", "Booking Marked No-Show"),
                            ("payment.received", "Payment Received"),
                            ("payment.failed", "Payment Failed"),
                            ("payment.refund_requested", "Refund Requested"),
                            ("payment.refund_succeeded", "Refund Succeeded"),
                            ("payment.refund_failed", "Refund Failed"),
                            ("email.sent", "Email Sent"),
                            ("email.failed", "Email Failed"),
                            ("pricing.settings_updated", "Pricing Settings Updated"),
                            ("pricing.rule_created", "Pricing Rule Created"),
                            ("pricing.rule_updated", "Pricing Rule Updated"),
                            ("pricing.rule_deleted", "Pricing Rule Deleted"),
                            ("team.member_invited", "Team Member Invited"),
                            ("team.member_role_changed", "Team Member Role Changed"),
                            ("team.member_deactivated", "Team Member Deactivated"),
                            ("team.member_reactivated", "Team Member Reactivated"),
                            ("role.created", "Role Created"),
                            ("role.updated", "Role Updated"),
                            ("role.deleted", "Role Deleted"),
                            ("role.permissions_changed", "Role Permissions Changed"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("booking", "Booking"),
                            ("payment", "Payment"),
                            ("refund", "Refund"),
                            ("email", "Email"),
                            ("pricing_settings", "Pricing Settings"),
                            ("pricing_rule", "Pricing Rule"),
                            ("role", "Role"),
                            ("permission", "Permission"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("resource_id", models.CharField(max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
            ],
            options={"db_table": "users_auditlog", "ordering": ["-timestamp"],},
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("bookings", "Bookings & Calendar"),
                            ("payments", "Payments & Invoices"),
                            ("guests", "Guests"),
                            ("pricing", "Pricing"),
                            ("team", "Team & Roles"),
                            ("reports", "Reports & Logs"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"db_table": "users_permission", "ordering": ["group", "code"],},
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_system", models.BooleanField(default=False)),
                ("is_super_admin", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "users_role", "ordering": ["name"],},
        ),
        migrations.AlterModelOptions(
            name="guestnote", options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(name="user", options={},),
        migrations.RemoveIndex(
            model_name="guestnote", name="users_guest_created_0ea4cd_idx",
        ),
        migrations.RemoveIndex(model_name="user", name="users_user_role_36d76d_idx",),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("guest", "Guest"),
                    ("team", "Team Member"),
                    ("admin", "Admin"),
                ],
                db_column="role",
                default="guest",
                max_length=10,
            ),
        ),
        migrations.RenameField(
            model_name="user", old_name="role", new_name="legacy_role",
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user", name="first_name", field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user", name="last_name", field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="permission",
            index=models.Index(fields=["code"], name="users_permi_code_cba410_idx"),
        ),
        migrations.AddIndex(
            model_name="permission",
            index=models.Index(fields=["group"], name="users_permi_group_53b03a_idx"),
        ),
        migrations.AddField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(
                blank=True, related_name="roles", to="users.permission"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="assigned_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="users.role",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["legacy_role"], name="users_user_role_36d76d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["assigned_role"], name="users_user_assigne_be21db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["-timestamp"], name="users_audit_timesta_f4ba63_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["user", "-timestamp"], name="users_audit_user_id_29b33e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action_type", "-timestamp"],
                name="users_audit_action__45998c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["resource_type", "resource_id"],
                name="users_audit_resourc_156f16_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["slug"], name="users_role_slug_997df9_idx"),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["is_super_admin"], name="users_role_is_supe_04abb0_idx"
            ),
        ),
    ]
