# Generated by Django 5.0.1 on 2025-11-28 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auditlog_permission_role_alter_guestnote_options_and_more"),
        ("users", "0003_passwordresettoken"),
    ]

    operations = []
