# Generated by Django 5.0.1 on 2025-11-29 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_reference_code_length"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="referralcredit",
            new_name="refcredit_referrer_created_idx",
            old_name="users_referralcredit_referrer_created_idx",
        ),
        migrations.RenameIndex(
            model_name="referralcredit",
            new_name="refcredit_referred_user_idx",
            old_name="users_referralcredit_referred_user_idx",
        ),
        migrations.RenameIndex(
            model_name="referralcredit",
            new_name="refcredit_status_idx",
            old_name="users_referralcredit_status_idx",
        ),
        migrations.RenameIndex(
            model_name="referralcredit",
            new_name="refcredit_booking_idx",
            old_name="users_referralcredit_booking_idx",
        ),
    ]
