# Generated by Django 5.0.1 on 2025-11-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_add_dashboard_permission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="group",
            field=models.CharField(
                choices=[
                    ("dashboard", "Dashboard & Analytics"),
                    ("bookings", "Bookings & Calendar"),
                    ("payments", "Payments & Invoices"),
                    ("guests", "Guests"),
                    ("pricing", "Pricing"),
                    ("team", "Team & Roles"),
                    ("reports", "Reports & Logs"),
                ],
                max_length=20,
            ),
        ),
    ]
