# Generated by Django 5.2 on 2025-12-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_populate_initial_hostprofile"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="review",
            new_name="users_revie_is_acti_c6a131_idx",
            old_name="users_revie_is_acti_985fa9_idx",
        ),
        migrations.RenameIndex(
            model_name="review",
            new_name="users_revie_is_feat_e6406f_idx",
            old_name="users_revie_is_feat_8e41c6_idx",
        ),
        migrations.AlterField(
            model_name="permission",
            name="group",
            field=models.CharField(
                choices=[
                    ("dashboard", "Dashboard & Analytics"),
                    ("bookings", "Bookings & Calendar"),
                    ("payments", "Payments & Invoices"),
                    ("guests", "Guests"),
                    ("pricing", "Pricing"),
                    ("team", "Team & Roles"),
                    ("gallery", "Gallery Management"),
                    ("reports", "Reports & Logs"),
                ],
                max_length=20,
            ),
        ),
    ]
