# Generated by Django 4.2.26 on 2025-12-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_referralcreditusage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="group",
            field=models.CharField(
                choices=[
                    ("dashboard", "Dashboard & Analytics"),
                    ("bookings", "Bookings & Calendar"),
                    ("payments", "Payments & Invoices"),
                    ("guests", "Guests"),
                    ("pricing", "Pricing"),
                    ("expenses", "Expense Management"),
                    ("team", "Team & Roles"),
                    ("gallery", "Gallery Management"),
                    ("reports", "Reports & Logs"),
                ],
                max_length=20,
            ),
        ),
    ]
