# Generated by Django 5.2 on 2025-12-11 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_booking_review_requested_at_booking_review_submitted_and_more'),
        ('users', '0018_alter_permission_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When review was approved', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who approved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='booking',
            field=models.ForeignKey(blank=True, help_text='Linked booking (if submitted via review request)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='review',
            name='edited_at',
            field=models.DateTimeField(blank=True, help_text='When review was last edited', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='edited_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who last edited', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='ota_source',
            field=models.CharField(choices=[('website', 'Website'), ('airbnb', 'Airbnb'), ('booking_com', 'Booking.com'), ('direct', 'Direct'), ('other', 'Other')], default='website', help_text='Booking source (auto-populated from booking or manual)', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='rating_accuracy',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Accuracy rating (0-10)', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='rating_checkin',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Check-in rating (0-10)', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='rating_cleanliness',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Cleanliness rating (0-10)', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='rating_communication',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Communication rating (0-10)', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='rating_location',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Location rating (0-10)', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='rating_value',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Value rating (0-10)', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='rejected_at',
            field=models.DateTimeField(blank=True, help_text='When review was rejected', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='rejected_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who rejected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Internal reason for rejection (not shown to guests)', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Review approval status', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='User who submitted (guest or staff member)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='permission',
            name='group',
            field=models.CharField(choices=[('dashboard', 'Dashboard & Analytics'), ('bookings', 'Bookings & Calendar'), ('payments', 'Payments & Invoices'), ('invoices', 'Invoice Management'), ('guests', 'Guests'), ('pricing', 'Pricing'), ('expenses', 'Expense Management'), ('team', 'Team & Roles'), ('gallery', 'Gallery Management'), ('reports', 'Reports & Logs'), ('reviews', 'Review Management')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['status'], name='users_revie_status_79f0c1_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['ota_source'], name='users_revie_ota_sou_c289e3_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['booking'], name='users_revie_booking_f7c7ad_idx'),
        ),
    ]
