# Generated by Django 5.2 on 2025-12-11 20:55

from django.db import migrations


def seed_review_permissions(apps, schema_editor):
    """
    Create 5 review permissions for the Review Management System.

    This creates permissions for:
    - reviews.view - View all reviews (pending, approved, rejected)
    - reviews.approve - Approve or reject pending reviews
    - reviews.create - Manually create reviews (staff-created)
    - reviews.edit - Edit existing reviews
    - reviews.delete - Permanently delete reviews
    """
    Permission = apps.get_model('users', 'Permission')

    review_permissions = [
        {
            'code': 'reviews.view',
            'group': 'reviews',
            'description': 'Can view all reviews (pending, approved, rejected)',
        },
        {
            'code': 'reviews.approve',
            'group': 'reviews',
            'description': 'Can approve or reject pending reviews',
        },
        {
            'code': 'reviews.create',
            'group': 'reviews',
            'description': 'Can manually create reviews (staff-created reviews)',
        },
        {
            'code': 'reviews.edit',
            'group': 'reviews',
            'description': 'Can edit existing reviews',
        },
        {
            'code': 'reviews.delete',
            'group': 'reviews',
            'description': 'Can permanently delete reviews',
        },
    ]

    for perm_data in review_permissions:
        Permission.objects.get_or_create(
            code=perm_data['code'],
            defaults={
                'group': perm_data['group'],
                'description': perm_data['description'],
            }
        )


def reverse_seed_permissions(apps, schema_editor):
    """Remove review permissions if migration is reversed."""
    Permission = apps.get_model('users', 'Permission')
    review_permission_codes = [
        'reviews.view',
        'reviews.approve',
        'reviews.create',
        'reviews.edit',
        'reviews.delete',
    ]
    Permission.objects.filter(code__in=review_permission_codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_review_approved_at_review_approved_by_review_booking_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_review_permissions, reverse_code=reverse_seed_permissions),
    ]
