# Generated by Django 4.2.26 on 2025-12-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_seed_review_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="referralcredit",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
