# Generated by Django 4.2.26 on 2025-12-06 15:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Short description of the expense", max_length=200
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("utilities", "Utilities"),
                            ("maintenance", "Maintenance & Repairs"),
                            ("cleaning", "Cleaning Supplies"),
                            ("amenities", "Guest Amenities"),
                            ("marketing", "Marketing & Advertising"),
                            ("software", "Software & Subscriptions"),
                            ("insurance", "Insurance"),
                            ("taxes", "Taxes & Fees"),
                            ("supplies", "Office Supplies"),
                            ("professional", "Professional Services"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Expense amount",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description or notes", null=True
                    ),
                ),
                (
                    "vendor",
                    models.CharField(
                        blank=True,
                        help_text="Vendor or payee name",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("card", "Credit/Debit Card"),
                            ("bank_transfer", "Bank Transfer"),
                            ("check", "Check"),
                            ("other", "Other"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                (
                    "expense_date",
                    models.DateField(help_text="Date when expense occurred"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                (
                    "receipt_url",
                    models.URLField(
                        blank=True, help_text="URL to receipt or invoice", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Team member who approved this expense",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Team member who created this expense record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "expenses_expense",
                "ordering": ["-expense_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["category"], name="expenses_ex_categor_fcaba7_idx"
                    ),
                    models.Index(
                        fields=["status"], name="expenses_ex_status_cbb790_idx"
                    ),
                    models.Index(
                        fields=["expense_date"], name="expenses_ex_expense_cf8a73_idx"
                    ),
                    models.Index(
                        fields=["created_by"], name="expenses_ex_created_bde1a5_idx"
                    ),
                ],
            },
        ),
    ]
