# Generated by Django 4.2.26 on 2025-12-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("gas", "Gas"),
                    ("electricity", "Electricity"),
                    ("water", "Water"),
                    ("internet", "Internet"),
                    ("garbage_fee", "Garbage Fee"),
                    ("insurance", "Insurance"),
                    ("maintenance", "Maintenance & Repairs"),
                    ("cleaning", "Cleaning Supplies"),
                    ("amenities", "Guest Amenities"),
                    ("marketing", "Marketing & Advertising"),
                    ("software", "Software & Subscriptions"),
                    ("taxes", "Taxes & Fees"),
                    ("supplies", "Office Supplies"),
                    ("professional", "Professional Services"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
