# Generated by Django 5.0.2 on 2025-11-26 07:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_type', models.CharField(choices=[('booking_confirmation', 'Booking Confirmation'), ('payment_receipt', 'Payment Receipt'), ('check_in_instructions', 'Check-in Instructions'), ('payment_link', 'Payment Link'), ('refund_confirmation', 'Refund Confirmation'), ('booking_cancellation', 'Booking Cancellation'), ('password_reset', 'Password Reset'), ('welcome_email', 'Welcome Email'), ('team_invitation', 'Team Invitation'), ('payment_failed', 'Payment Failed'), ('pre_arrival_reminder', 'Pre-arrival Reminder'), ('post_stay_thankyou', 'Post-stay Thank You'), ('invoice_email', 'Invoice Email')], max_length=50)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zeptomail_message_id', models.CharField(blank=True, max_length=255)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'db_table': 'emails_emaillog',
                'ordering': ['-created_at'],
            },
        ),
    ]
