# Generated by Django 5.0.2 on 2025-11-26 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emails', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['email_type'], name='emails_emai_email_t_10c22d_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['status'], name='emails_emai_status_e97e19_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['created_at'], name='emails_emai_created_8a5fea_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['recipient_email'], name='emails_emai_recipie_8fd7a7_idx'),
        ),
    ]
