# Generated by Django 5.0.1 on 2025-11-27 20:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_alter_blockeddate_options_alter_booking_options_and_more"),
        ("emails", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emaillog", options={"ordering": ["-sent_at"]},
        ),
        migrations.RemoveIndex(
            model_name="emaillog", name="emails_emai_email_t_10c22d_idx",
        ),
        migrations.RemoveIndex(
            model_name="emaillog", name="emails_emai_status_e97e19_idx",
        ),
        migrations.RemoveIndex(
            model_name="emaillog", name="emails_emai_created_8a5fea_idx",
        ),
        migrations.RemoveField(model_name="emaillog", name="created_at",),
        migrations.RemoveField(model_name="emaillog", name="email_type",),
        migrations.RemoveField(model_name="emaillog", name="recipient_name",),
        migrations.RemoveField(model_name="emaillog", name="user",),
        migrations.RemoveField(model_name="emaillog", name="zeptomail_message_id",),
        migrations.AddField(
            model_name="emaillog",
            name="from_email",
            field=models.EmailField(
                default="support@allarcoapartment.com", max_length=254
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emaillog",
            name="template_name",
            field=models.CharField(default="generic", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="sent_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="status",
            field=models.CharField(
                choices=[
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("bounced", "Bounced"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="emaillog",
            index=models.Index(
                fields=["booking"], name="emails_emai_booking_5e959d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emaillog",
            index=models.Index(
                fields=["template_name"], name="emails_emai_templat_0c7c8a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emaillog",
            index=models.Index(
                fields=["sent_at"], name="emails_emai_sent_at_09db08_idx"
            ),
        ),
    ]
