# Generated by Django 5.0.1 on 2025-11-27 20:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_alter_blockeddate_options_alter_booking_options_and_more"),
        ("invoices", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice", options={"ordering": ["-issue_date"]},
        ),
        migrations.RemoveIndex(
            model_name="invoice", name="invoices_in_issued__25a89d_idx",
        ),
        migrations.RenameField(
            model_name="invoice", old_name="accommodation_total", new_name="amount",
        ),
        migrations.RenameField(
            model_name="invoice", old_name="issued_at", new_name="created_at",
        ),
        migrations.RemoveField(model_name="invoice", name="cleaning_fee",),
        migrations.RemoveField(model_name="invoice", name="created_by",),
        migrations.RemoveField(model_name="invoice", name="extra_guest_fee",),
        migrations.RemoveField(model_name="invoice", name="payment",),
        migrations.RemoveField(model_name="invoice", name="pdf_generated_at",),
        migrations.RemoveField(model_name="invoice", name="total_amount",),
        migrations.RemoveField(model_name="invoice", name="tourist_tax",),
        migrations.AddField(
            model_name="invoice",
            name="issue_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="bookings.booking",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="pdf_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("sent", "Sent"),
                    ("paid", "Paid"),
                    ("overdue", "Overdue"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["booking"], name="invoices_in_booking_a98bc7_idx"
            ),
        ),
    ]
