# Generated by Django 4.2.26 on 2025-12-02 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0004_company"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="company",
            new_name="invoices_co_name_718e71_idx",
            old_name="invoices_c_name_e56054_idx",
        ),
        migrations.RenameIndex(
            model_name="company",
            new_name="invoices_co_vat_num_f961fd_idx",
            old_name="invoices_c_vat_numb_ef9393_idx",
        ),
        migrations.RenameIndex(
            model_name="company",
            new_name="invoices_co_country_bf7a36_idx",
            old_name="invoices_c_country_a76436_idx",
        ),
    ]
