# Generated by Django 4.2.26 on 2025-12-03 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "invoices",
            "0005_rename_invoices_c_name_e56054_idx_invoices_co_name_718e71_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Required for invoice type, optional for receipt",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="invoices.company",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("card", "Card"),
                    ("bank_transfer", "Bank Transfer"),
                    ("property", "At Property"),
                    ("stripe", "Stripe"),
                ],
                default="property",
                help_text="Payment method for this invoice/receipt",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="type",
            field=models.CharField(
                choices=[("invoice", "Invoice"), ("receipt", "Receipt")],
                default="receipt",
                max_length=20,
            ),
        ),
    ]
