# Generated by Django 4.2.26 on 2025-12-10 20:17

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("invoices", "0006_invoice_company_invoice_payment_method_invoice_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="contact_person_email",
            field=models.EmailField(
                blank=True,
                help_text="Contact email (may differ from company email)",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="contact_person_name",
            field=models.CharField(
                blank=True, help_text="Primary contact at company", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="contact_person_phone",
            field=models.CharField(
                blank=True, help_text="Contact phone number", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="invoice_count",
            field=models.IntegerField(
                default=0, help_text="Cache of total invoices issued"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Soft delete / archive companies"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="last_invoice_date",
            field=models.DateField(
                blank=True, help_text="Last invoice issued date", null=True
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Internal notes about company"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="tags",
            field=models.JSONField(
                blank=True, default=list, help_text="Tags for categorization"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="total_invoiced",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Cache of total amount invoiced",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Team member who created this invoice",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="last_sent_at",
            field=models.DateTimeField(
                blank=True, help_text="Last email send timestamp", null=True
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="line_items",
            field=models.JSONField(
                blank=True, default=list, help_text="Custom line items as JSON array"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                help_text="PDF file storage",
                null=True,
                upload_to="invoices/",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="sent_count",
            field=models.IntegerField(
                default=0, help_text="Number of times email was sent"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="sent_to_email",
            field=models.EmailField(
                blank=True,
                help_text="Email address where invoice was sent",
                max_length=254,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="CompanyNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("general", "General Note"),
                            ("call", "Phone Call"),
                            ("email", "Email"),
                            ("meeting", "Meeting"),
                            ("issue", "Issue/Problem"),
                            ("resolution", "Resolution"),
                        ],
                        default="general",
                        help_text="Type of interaction or note",
                        max_length=50,
                    ),
                ),
                ("content", models.TextField(help_text="Note content")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company this note belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_notes",
                        to="invoices.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Team member who created this note",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="company_notes_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "invoices_company_note",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "-created_at"],
                        name="invoices_co_company_363de4_idx",
                    ),
                    models.Index(
                        fields=["note_type"], name="invoices_co_note_ty_e7438d_idx"
                    ),
                ],
            },
        ),
    ]
