# Generated by Django 4.2.26 on 2025-12-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_payment_options_alter_refund_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="kind",
            field=models.CharField(
                choices=[("booking", "Booking"), ("city_tax", "City Tax")],
                default="booking",
                max_length=20,
            ),
        ),
    ]
