# Generated by Django 4.2.26 on 2025-12-10 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "bookings",
            "0015_booking_alloggiati_sent_booking_alloggiati_sent_at_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0004_payment_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("deposit", "Security Deposit"),
                            ("remaining_balance", "Remaining Balance"),
                            ("additional_charge", "Additional Charge"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="EUR", max_length=3)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "stripe_payment_link_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "stripe_payment_link_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                            ("overdue", "Overdue"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_requests",
                        to="bookings.booking",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_requests_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payments_payment_request",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["booking"], name="payments_pa_booking_fe9b91_idx"
                    ),
                    models.Index(
                        fields=["status"], name="payments_pa_status_03f4b7_idx"
                    ),
                    models.Index(
                        fields=["due_date"], name="payments_pa_due_dat_d76b04_idx"
                    ),
                    models.Index(
                        fields=["stripe_payment_link_id"],
                        name="payments_pa_stripe__0b2e13_idx",
                    ),
                ],
            },
        ),
    ]
