# Generated by Django 5.2 on 2025-12-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_paymentrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='kind',
            field=models.CharField(choices=[('booking', 'Booking'), ('city_tax', 'City Tax'), ('custom', 'Custom Payment')], default='booking', max_length=20),
        ),
    ]
